<?php

/**
 * @file
 * Contains social_json_api.module.
 */

/**
 * Implements hook_entity_type_alter().
 */
function social_json_api_entity_type_alter(array &$entity_types) {
  $allow = [
    'comment',
    'event_enrollment',
    'file',
    'group',
    'group_content',
    'node',
    'post',
    'profile',
    'taxonomy_term',
    'user',
  ];

  /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
  foreach ($entity_types as $entity_name => $entity_type) {
    /** @var $entity_type \Drupal\Core\Entity\EntityTypeInterface */
    if (in_array($entity_name, $allow, TRUE) !== TRUE) {
      $entity_type->set('internal', TRUE);
    }
  }
}
